config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  post '/do_something', to: 'welcome#do_something'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operation.rb
class Operation
  include NoBrainer::Document
  field :progress, type: Integer, required: true, default: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  expose :operation, :load_operation

  def index
  end

  def do_something
    operation.progress += 1
    operation.save!
    render json: {status: 'OK'}
  end

  private

  def load_operation
    if session[:operation_id]
      Operation.find(session[:operation_id])
    else
      Operation.create.tap do |op|
        session[:operation_id] = op.id
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def livestatus_url(operation_id)
    ENV.fetch('DOCKHERO_FLEXIBLE_SSL_URL') + "/operations/#{operation_id}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logsfeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.1.0/rx.all.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/rxjs-dom/7.0.3/rx.dom.min.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<%= riot_component(:progressor, {feed_url: livestatus_url(operation.id)}) %>

<%= button_to "Do Something", do_something_path, remote: true %>